### ISSUE TITLE
Stop to work in Firefox 54.0 (64-bit) Ubuntu 16

### ISSUE THREAD

**Issue by danielbchaves** [mjgiarlo/jsonovich#44] opened 2017-08-09 17:23 UTC
I always used this addon and it suddenly stops to work, JSON's are just a plain text now.

I am using FF 54 and Ubuntu, tried to reinstall addon, getting version 1.99.4 from July 6, 2017, reopened browser but nothing changes.

Tried do chance settings in firefox (about:config) but the problem still happens with true or false 
devtools.jsonview.enabled = false

Tested in many services and here is a simple online test http://headers.jsontest.com/

**Comment by hackel** [comment] 2017-08-18 23:31
Confirmed, running FF 56.0b3.  I assume this is related to #43.  Also, just to clarify, I'm referring to displaying JSON content in the browser itself, not in the developer tools.

Thanks for continuing this project @welwood08!

**Comment by welwood08** [comment] 2017-08-19 03:32
For some reason my GitHub notifications were set not to email me for watched repos, so thanks for mentioning me directly - fixed that for future issues.

This is a duplicate of #39 that resurfaced in the new webext implementation (technically that test site is sending invalid JSON because the charset should always be UTF-8). I did fix it in source a day after submitting to AMO, but the AMO review unexpectedly took a month so I'd forgotten the fix needed to be pushed. Sorry about that, I'll try to squeeze a few more fixes in and push a new version to AMO some time this weekend.

**Comment by welwood08** [comment] 2017-08-20 14:08
1.99.5 approved.

**Closed by welwood08** 2017-08-20 14:08 UTC
